name: tickets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  path: ^1.8.3
  uuid: ^4.0.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  provider: ^6.1.5
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder_unavailable.png
    - assets/images/placeholder_failed.png
    - assets/images/placeholder_retry.png
