// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0X5Bh8-HoFwKndpBP7v51zF3QiblhqbM',
    appId: '1:841651611010:web:2f6821e4b411d4d3e5db9b',
    messagingSenderId: '841651611010',
    projectId: 'tikets-1283e',
    authDomain: 'tikets-1283e.firebaseapp.com',
    storageBucket: 'tikets-1283e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrXtgAmRBuQjO75rnQbdWE-liu55KfbI',
    appId: '1:841651611010:android:2eada64ca3cb6d71e5db9b',
    messagingSenderId: '841651611010',
    projectId: 'tikets-1283e',
    storageBucket: 'tikets-1283e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJ_pubqOV_MdtO8Vwq2n1ejZBLFLHMSU',
    appId: '1:841651611010:ios:1f9562fc660ac29ee5db9b',
    messagingSenderId: '841651611010',
    projectId: 'tikets-1283e',
    storageBucket: 'tikets-1283e.firebasestorage.app',
    iosBundleId: 'com.example.tickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJ_pubqOV_MdtO8Vwq2n1ejZBLFLHMSU',
    appId: '1:841651611010:ios:1f9562fc660ac29ee5db9b',
    messagingSenderId: '841651611010',
    projectId: 'tikets-1283e',
    storageBucket: 'tikets-1283e.firebasestorage.app',
    iosBundleId: 'com.example.tickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0X5Bh8-HoFwKndpBP7v51zF3QiblhqbM',
    appId: '1:841651611010:web:45c5fd30abf6356ae5db9b',
    messagingSenderId: '841651611010',
    projectId: 'tikets-1283e',
    authDomain: 'tikets-1283e.firebaseapp.com',
    storageBucket: 'tikets-1283e.firebasestorage.app',
  );
}
